#!/bin/bash
set -euo pipefail

CONFIG_FILE="${DEVCONTAINER_CONFIG:-/workspace/.devcontainer/config.toml}"
ENV_FILE="/etc/profile.d/devcontainer-env.sh"

# ── Helper: read a TOML value (returns empty string if missing) ──
toml_get() {
    local result
    result=$(cat "$CONFIG_FILE" | dasel -i toml "$1" 2>/dev/null | sed "s/^'//;s/'$//") || result=""
    echo "$result"
}

# ── Helper: export and persist an env var ──
set_env() {
    local name="$1" value="$2"
    if [ -n "$value" ]; then
        export "$name=$value"
        echo "export $name=$(printf '%q' "$value")" >> "$ENV_FILE"
    fi
}

# ── Wait for config file (volume may mount slightly after start) ──
WAIT_SECONDS=5
for i in $(seq 1 "$WAIT_SECONDS"); do
    [ -f "$CONFIG_FILE" ] && break
    sleep 1
done

# Initialize env file
echo "# Auto-generated by devcontainer entrypoint" > "$ENV_FILE"

if [ -f "$CONFIG_FILE" ]; then
    echo "[devcontainer] Reading config from $CONFIG_FILE"

    # ── Git (required) ──
    GIT_NAME=$(toml_get "git.name")
    GIT_EMAIL=$(toml_get "git.email")

    if [ -z "$GIT_NAME" ] || [ -z "$GIT_EMAIL" ]; then
        echo "[devcontainer] ERROR: [git] name and email are required in $CONFIG_FILE"
        exit 1
    fi

    git config --global user.name "$GIT_NAME"
    git config --global user.email "$GIT_EMAIL"
    echo "[devcontainer] Git configured: $GIT_NAME <$GIT_EMAIL>"

    # ── Claude Code ──
    CLAUDE_KEY=$(toml_get "claude.api_key")
    set_env "ANTHROPIC_API_KEY" "$CLAUDE_KEY"

    # ── Codex CLI ──
    CODEX_KEY=$(toml_get "codex.api_key")
    set_env "OPENAI_API_KEY" "$CODEX_KEY"

    # ── GitHub CLI ──
    GH_TOKEN=$(toml_get "github.token")
    if [ -n "$GH_TOKEN" ]; then
        set_env "GITHUB_TOKEN" "$GH_TOKEN"
        echo "$GH_TOKEN" | gh auth login --with-token 2>/dev/null \
            && echo "[devcontainer] GitHub CLI authenticated" \
            || echo "[devcontainer] WARNING: gh auth login failed"
    fi

    # ── AWS CLI ──
    AWS_KEY=$(toml_get "aws.access_key_id")
    AWS_SECRET=$(toml_get "aws.secret_access_key")
    AWS_REGION=$(toml_get "aws.region")
    AWS_REGION="${AWS_REGION:-us-east-1}"

    if [ -n "$AWS_KEY" ] && [ -n "$AWS_SECRET" ]; then
        set_env "AWS_ACCESS_KEY_ID" "$AWS_KEY"
        set_env "AWS_SECRET_ACCESS_KEY" "$AWS_SECRET"
        set_env "AWS_DEFAULT_REGION" "$AWS_REGION"
        echo "[devcontainer] AWS CLI configured (region: $AWS_REGION)"
    fi

    # ── MySQL socket ──
    MYSQL_SOCKET=$(toml_get "mysql.socket")
    if [ -n "$MYSQL_SOCKET" ]; then
        set_env "MYSQL_UNIX_PORT" "$MYSQL_SOCKET"
        if [ -S "$MYSQL_SOCKET" ]; then
            echo "[devcontainer] MySQL socket found: $MYSQL_SOCKET"
        else
            echo "[devcontainer] MySQL socket configured but not yet available: $MYSQL_SOCKET"
        fi
    fi

    # ── PostgreSQL socket ──
    PG_SOCKET=$(toml_get "postgresql.socket")
    if [ -n "$PG_SOCKET" ]; then
        set_env "PGHOST" "$PG_SOCKET"
        if [ -d "$PG_SOCKET" ]; then
            echo "[devcontainer] PostgreSQL socket dir found: $PG_SOCKET"
        else
            echo "[devcontainer] PostgreSQL socket dir configured but not yet available: $PG_SOCKET"
        fi
    fi

    # ── Post-start hook ──
    POST_START=$(toml_get "hooks.post_start")
    if [ -n "$POST_START" ]; then
        echo "[devcontainer] Running post_start hook: $POST_START"
        bash -c "$POST_START" || echo "[devcontainer] WARNING: post_start hook failed"
    fi

else
    echo "[devcontainer] No config file found at $CONFIG_FILE — skipping configuration"
    echo "[devcontainer] Create one from example.config.toml to enable auto-configuration"
fi

exec "$@"
